language: ruby
sudo: false
cache: bundler
before_install:
  - gem install bundler
script:
  - bundle exec rake test
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6.1
  - ruby-head
  - jruby-head
  - rbx-3
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-3
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a44b19cc5cf6db25fa87
    on_success: change
    on_failure: always
    on_start: never
